### ISSUE TITLE
trouble with the RNG example in the tutorial

### ISSUE THREAD

**Issue by tbcdebug** [Huawei-HiQ/HiQsimulator#11]
I was trying the random number generator example in the [tutorial](https://hiqsimulator.readthedocs.io/en/latest/tutorials/tutorials.local.html) and could not proceed. The aborting message is as follows, of which `ImportError: No module named 'hiq.projectq.backends._sim._cppsim_mpi'` might be the problem.
```
mpirun -np 2 python3 random_number.py
Traceback (most recent call last):
  File "random_number.py", line 2, in <module>
    from hiq.projectq.backends import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/__init__.py", line 25, in <module>
    from ._sim import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/__init__.py", line 15, in <module>
    from ._simulator_mpi import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/_simulator_mpi.py", line 39, in <module>
    from ._cppsim_mpi import SimulatorMPI as SimulatorBackend
ImportError: No module named 'hiq.projectq.backends._sim._cppsim_mpi'
Traceback (most recent call last):
  File "random_number.py", line 2, in <module>
    from hiq.projectq.backends import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/__init__.py", line 25, in <module>
    from ._sim import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/__init__.py", line 15, in <module>
    from ._simulator_mpi import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/_simulator_mpi.py", line 39, in <module>
    from ._cppsim_mpi import SimulatorMPI as SimulatorBackend
ImportError: No module named 'hiq.projectq.backends._sim._cppsim_mpi'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31690,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by Huawei-HiQ** [comment]
Can you show the the running log of "python3 -m pip install --user ." It seems that you have not successfully installed hiq.

**Comment by tbcdebug** [comment]
```
python3 -m pip install --user .
Processing /home/parallels/quantum_computing/hw_contest/HiQsimulator
Requirement already satisfied: mpi4py in /home/parallels/.local/lib/python3.5/site-packages (from HiQsimulator==0.0.1) (3.0.2)
Requirement already satisfied: projectq>=0.4.0 in /home/parallels/.local/lib/python3.5/site-packages (from HiQsimulator==0.0.1) (0.4.2)
Requirement already satisfied: numpy in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (1.16.4)
Requirement already satisfied: future in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (0.17.1)
Requirement already satisfied: pytest>=3.1 in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (5.0.1)
Requirement already satisfied: pybind11>=2.2.3 in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.3.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.9.1)
Requirement already satisfied: scipy in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (1.3.0)
Requirement already satisfied: networkx in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.3)
Requirement already satisfied: packaging in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (19.0)
Requirement already satisfied: attrs>=17.4.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (19.1.0)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (2.3.4)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.12.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.3.0)
Requirement already satisfied: py>=1.5.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.8.0)
Requirement already satisfied: wcwidth in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.1.7)
Requirement already satisfied: more-itertools>=4.0.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (7.1.0)
Requirement already satisfied: importlib-metadata>=0.12 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.18)
Requirement already satisfied: decorator>=4.3.0 in /home/parallels/.local/lib/python3.5/site-packages (from networkx->projectq>=0.4.0->HiQsimulator==0.0.1) (4.4.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from packaging->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.10.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (2.0.3)
Requirement already satisfied: zipp>=0.5 in /home/parallels/.local/lib/python3.5/site-packages (from importlib-metadata>=0.12->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.5.2)
Building wheels for collected packages: HiQsimulator
  Building wheel for HiQsimulator (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-1y3usqcr/wheels/31/26/9e/2dd1d8570e0dccae627ecd8a04d43f98b59b2d63ad932fae91
Successfully built HiQsimulator
Installing collected packages: HiQsimulator
  Found existing installation: HiQsimulator 0.0.1
    Uninstalling HiQsimulator-0.0.1:
      Successfully uninstalled HiQsimulator-0.0.1
Successfully installed HiQsimulator-0.0.1

```

**Comment by tbcdebug** [comment]
and I tried RNG again
```
python3 random_number.py 
Traceback (most recent call last):
  File "random_number.py", line 2, in <module>
    from hiq.projectq.backends import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/__init__.py", line 25, in <module>
    from ._sim import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/__init__.py", line 15, in <module>
    from ._simulator_mpi import SimulatorMPI
  File "/home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/projectq/backends/_sim/_simulator_mpi.py", line 39, in <module>
    from ._cppsim_mpi import SimulatorMPI as SimulatorBackend
ImportError: No module named 'hiq.projectq.backends._sim._cppsim_mpi'
```

**Comment by Takishima** [comment]
Is it possible that there’s a missing __init__.py file in the `ProjectQ` folder?

**Comment by tbcdebug** [comment]
It looks like some file named `_cppsim_mpi.py` is missing in `hiq/projectq/backends/_sim`, and this file is required by `_simulator_mpi.py`.

**Comment by Huawei-HiQ** [comment]
Also, don't put the test case in the root directory of the HiQsimulator code, this will cause Python to find the lib path error.

**Comment by Huawei-HiQ** [comment]
Your python package installation directory is /home/parallels/.local/lib/python3.5/site-packages, but the directory for import hiq is: /home/parallels/quantum_computing/hw_contest/HiQsimulator/hiq/

**Comment by tbcdebug** [comment]
So how should the directory of hiq be

**Comment by Huawei-HiQ** [comment]
/home/parallels/.local/lib/python3.5/site-packages/hiq/

**Comment by tbcdebug** [comment]
Alright I change to that. This is the log. However, the RNG is still not working. I find that it crashes on `Measure | q1`, and then it says "Illegal Instruction“
```
Processing /home/parallels/.local/lib/python3.5/site-packages/HiQsimulator
Requirement already satisfied: mpi4py in /home/parallels/.local/lib/python3.5/site-packages (from HiQsimulator==0.0.1) (3.0.2)
Requirement already satisfied: projectq>=0.4.0 in /home/parallels/.local/lib/python3.5/site-packages (from HiQsimulator==0.0.1) (0.4.2)
Requirement already satisfied: numpy in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (1.16.4)
Requirement already satisfied: future in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (0.17.1)
Requirement already satisfied: pytest>=3.1 in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (5.0.1)
Requirement already satisfied: pybind11>=2.2.3 in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.3.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.9.1)
Requirement already satisfied: scipy in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (1.3.0)
Requirement already satisfied: networkx in /home/parallels/.local/lib/python3.5/site-packages (from projectq>=0.4.0->HiQsimulator==0.0.1) (2.3)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.12.0)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (2.3.4)
Requirement already satisfied: attrs>=17.4.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (19.1.0)
Requirement already satisfied: importlib-metadata>=0.12 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.18)
Requirement already satisfied: atomicwrites>=1.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.3.0)
Requirement already satisfied: wcwidth in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.1.7)
Requirement already satisfied: more-itertools>=4.0.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (7.1.0)
Requirement already satisfied: py>=1.5.0 in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.8.0)
Requirement already satisfied: packaging in /home/parallels/.local/lib/python3.5/site-packages (from pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (19.0)
Requirement already satisfied: decorator>=4.3.0 in /home/parallels/.local/lib/python3.5/site-packages (from networkx->projectq>=0.4.0->HiQsimulator==0.0.1) (4.4.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (1.10.0)
Requirement already satisfied: zipp>=0.5 in /home/parallels/.local/lib/python3.5/site-packages (from importlib-metadata>=0.12->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (0.5.2)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest>=3.1->projectq>=0.4.0->HiQsimulator==0.0.1) (2.0.3)
Building wheels for collected packages: HiQsimulator
  Building wheel for HiQsimulator (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-dfba0wwg/wheels/06/08/c3/94d9df36a2c511551421092d01330fc2d69024e69c7f2bb6c3
Successfully built HiQsimulator
Installing collected packages: HiQsimulator
  Found existing installation: HiQsimulator 0.0.1
    Uninstalling HiQsimulator-0.0.1:
      Successfully uninstalled HiQsimulator-0.0.1
Successfully installed HiQsimulator-0.0.1
```

**Comment by Huawei-HiQ** [comment]
Can you successfully execute the examples in HiQsimulator/examples/

**Comment by tbcdebug** [comment]
No, for example the teleportation
```
==================================================================
= This is the Teleportation algorithm demo
= Change the state to send by modifying create_state function
= It is assumed that Alice and Bob share a Bell-pair in advance
= Step 1. Alice creates the state to be sent from |0>
= Step 2. Alice entangles the state with her share of the Bell-pair
非法指令 (核心已转储)
```

**Comment by tbcdebug** [comment]
I can actually run project q program on my computer
```
from projectq import MainEngine  # import the main compiler engine
from projectq.ops import H, Measure  # import the operations we want to perform (Hadamard and measurement)

eng = MainEngine()  # create a default compiler (the back-end is a simulator)
qubit = eng.allocate_qubit()  # allocate 1 qubit

H | qubit  # apply a Hadamard gate
Measure | qubit  # measure the qubit

eng.flush()  # flush all gates (and execute measurements)
print("Measured {}".format(int(qubit)))  # output measurement result```

**Comment by Takishima** [comment]
If you go to the `/home/parallels/.local/lib/python3.5/site-packages/hiq/projectq/backends/_sim/` do you see any shared library files (*.so) ?

Otherwise, you might want to try this

```bash
python3 setup.py install
```

**Comment by Takishima** [comment]
Any update on your problem? Were you able to solve it? If not, what is your current status?

**Comment by tbcdebug** [comment]
I wanted to use HiQ during the contest. I did not manage to solve this problem, so I just used ProjectQ during the contest. Now that the contest is over, I stopped digging into the problem, and do not plan to resume doing so for the time being. I can close the issue if you want.

**Comment by keithyau** [comment]
same issue

![image](https://user-images.githubusercontent.com/659311/136756916-c4a9d179-8c69-48b6-ad45-f74936f778af.png)

**Comment by Takishima** [comment]
Do you have Boost::MPI installed on your system ?

**Comment by keithyau** [comment]
I have this one 
sudo apt-get -y install libboost-mpi-dev
