### ISSUE TITLE
Install HiQ on Ubuntu16.04

### ISSUE THREAD

**Issue by ShuaiHanSelf-discipline** [Huawei-HiQ/HiQsimulator#34]
I installed HiQ with the following command(Official tutorial), there was an error prompt message, but I solved it and installed it successfully.Here are the details. Hope the official tutorial is getting better and better.
install command
`
  sudo apt-get update
  sudo apt-get install libboost-all-dev
  sudo apt-get install build-essential cmake
  sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
  sudo apt-get install libboost-all-dev
  sudo apt-get install libgoogle-glog-dev
  sudo apt-get install python3 python3-pip
  git clone --recursive https://github.com/Huawei-HiQ/HiQsimulator.git
  cd HiQsimulator
  python3 -m pip install --user .  `

When I use the following test command  to test whether the installation is successful, I encounter the following error prompt message.
Test command 
 `mpirun -np 2 python3 ./examples/teleport_mpi.py`

Error prompt message 

`Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./examples/teleport_mpi.py", line 1, in <module>
    from projectq.ops import All, CNOT, H, Measure, Rz, X, Z
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/__init__.py", line 29, in <module>
    from projectq.cengines import MainEngine
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/cengines/__init__.py", line 20, in <module>
    from ._ibm5qubitmapper import IBM5QubitMapper
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/cengines/_ibm5qubitmapper.py", line 22, in <module>
    from projectq.backends import IBMBackend
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/__init__.py", line 29, in <module>
    from ._circuits import CircuitDrawer, CircuitDrawerMatplotlib
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/_circuits/__init__.py", line 16, in <module>
    from ._plot import to_draw
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/_circuits/_plot.py", line 28, in <module>
    import matplotlib.pyplot as plt
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./examples/teleport_mpi.py", line 1, in <module>
    from projectq.ops import All, CNOT, H, Measure, Rz, X, Z
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/__init__.py", line 29, in <module>
    from projectq.cengines import MainEngine
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/cengines/__init__.py", line 20, in <module>
    from ._ibm5qubitmapper import IBM5QubitMapper
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/cengines/_ibm5qubitmapper.py", line 22, in <module>
    from projectq.backends import IBMBackend
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/__init__.py", line 29, in <module>
    from ._circuits import CircuitDrawer, CircuitDrawerMatplotlib
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/_circuits/__init__.py", line 16, in <module>
    from ._plot import to_draw
  File "/home/quantum01/.local/lib/python3.5/site-packages/projectq/backends/_circuits/_plot.py", line 28, in <module>
    import matplotlib.pyplot as plt
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/quantum01/.local/lib/python3.5/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19585,1],0]
  Exit code:    1`

Then I ran the following command to solve this problem
`sudo apt-get install python3-tk`

This is the result of a successful test.

` quantum01@quantum506:~/HiQsimulator$ mpirun -np 2 python3 ./examples/teleport_mpi.py
==================================================================
= This is the Teleportation algorithm demo
= Change the state to send by modifying create_state function
==================================================================
= This is the Teleportation algorithm demo
= Change the state to send by modifying create_state function
= It is assumed that Alice and Bob share a Bell-pair in advance
= It is assumed that Alice and Bob share a Bell-pair in advance
= Step 1. Alice creates the state to be sent from |0>
= Step 1. Alice creates the state to be sent from |0>
= Step 2. Alice entangles the state with her share of the Bell-pair
= Step 2. Alice entangles the state with her share of the Bell-pair
= Step 3. Alice sends the classical message [1, 0] to Bob
= Step 3. Alice sends the classical message [1, 0] to Bob
= Step 4. Bob tries to recover the state created by Alice
= Step 4. Bob tries to recover the state created by Alice
	 Bob successfully arrived at |0>
	 Bob successfully arrived at |0>
==================================================================
==================================================================
`

**Comment by Takishima** [comment]
Thanks for letting us know of that issue. I have submitted a PR to address that issue in the tutorial.
