### ISSUE TITLE
Installation of HiQ by using pip failed

### ISSUE THREAD

**Issue by DechinPhy** [Huawei-HiQ/HiQsimulator#40]
When I run `pip install hiq-circuit` in my python virtual environment it failed.

**Comment by DechinPhy** [comment]
```
(hiq) (base) dechin@dechin-PC:~/git_lab$ python3 -m pip install hiq-circuit
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting hiq-circuit
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/45/c1/39453dd9e61db6e14cb5116f86788b18ca15c9794593fee46fc258715283/hiq-circuit-0.0.2.tar.gz (381 kB)
Collecting mpi4py
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/8f/bbd8de5ba566dd77e408d8136e2bab7fdf2b97ce06cab830ba8b50a2f588/mpi4py-3.0.3.tar.gz (1.4 MB)
Collecting hiq-projectq>=0.6.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cd/e8/310e6413208a6dd1a54ef3be324a625e0531848a90931438fea43b245d02/hiq-projectq-0.6.3.tar.gz (159 kB)
Collecting numpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d6/c6/58e517e8b1fb192725cfa23c01c2e60e4e6699314ee9684a1c5f5c9b27e1/numpy-1.18.5-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
Processing /home/dechin/.cache/pip/wheels/bc/6f/cd/f72c82ed44590b04c6deb82b177f0d260aec8621f6568e0368/future-0.18.2-py3-none-any.whl
Collecting pytest>=3.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9f/f3/0a83558da436a081344aa6c8b85ea5b5f05071214106036ce341b7769b0b/pytest-5.4.3-py3-none-any.whl (248 kB)
Collecting pybind11>=2.2.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/89/e3/d576f6f02bc75bacbc3d42494e8f1d063c95617d86648dba243c2cb3963e/pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
Collecting requests
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting scipy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/dd/82/c1fe128f3526b128cfd185580ba40d01371c5d299fcf7f77968e22dfcc2e/scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
     |████████████████████████████████| 26.1 MB 160 kB/s 
Collecting networkx
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 11.4 MB/s 
Collecting matplotlib>=2.2.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b2/c2/71fcf957710f3ba1f09088b35776a799ba7dd95f7c2b195ec800933b276b/matplotlib-3.2.1-cp37-cp37m-manylinux1_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 48 kB/s 
Requirement already satisfied: setuptools>=40.1.0 in ./hiq/lib/python3.7/site-packages (from hiq-projectq>=0.6.0->hiq-circuit) (46.4.0)
Collecting wcwidth
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ef/94/a17155b400812f0558093c6fb99f92ba823e24757d5884e3ec60f5e81319/wcwidth-0.2.4-py2.py3-none-any.whl (30 kB)
Collecting attrs>=17.4.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting more-itertools>=4.0.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ef/9b/6c35ec5483710492e21252465160ee508170159f7e0e2d6cd769022f52f6/more_itertools-8.4.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 4.9 MB/s 
Collecting py>=1.5.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ae/12/76710702ccf77dab01246ecb55fbe43175131c0738d0be29f3de50d31071/py-1.8.2-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 4.6 MB/s 
Collecting packaging
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting pluggy<1.0,>=0.12
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/98/13/a1d703ec396ade42c1d33df0e1cb691a28b7c08b336a5683912c87e04cd7/importlib_metadata-1.6.1-py2.py3-none-any.whl (31 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 10.3 MB/s 
Collecting idna<3,>=2.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 46 kB/s 
Collecting chardet<4,>=3.0.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/98/99/def511020aa8f663d4a2cfaa38467539e864799289ff354569e339e375b1/certifi-2020.4.5.2-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 28 kB/s 
Collecting decorator>=4.3.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 83 kB/s 
Collecting cycler>=0.10
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 99 kB/s 
Collecting kiwisolver>=1.0.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/31/b9/6202dcae729998a0ade30e80ac00f616542ef445b088ec970d407dfd41c0/kiwisolver-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 308 kB/s 
Collecting six
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl (4.9 kB)
Building wheels for collected packages: hiq-circuit, mpi4py, hiq-projectq
  Building wheel for hiq-circuit (setup.py) ... done
  Created wheel for hiq-circuit: filename=hiq_circuit-0.0.2-cp37-cp37m-linux_x86_64.whl size=342871 sha256=dbfadef1f0f5ab63a05a00c96826aae649840a91b58377dc67821caf07362dab
  Stored in directory: /home/dechin/.cache/pip/wheels/22/d4/c4/cc1ea421636928c37684442333ea45fc03da2db32b973d210e
  Building wheel for mpi4py (setup.py) ... done
  Created wheel for mpi4py: filename=mpi4py-3.0.3-cp37-cp37m-linux_x86_64.whl size=2137281 sha256=0783262b7b3a0b43d9f10a851add87752b03a288c9712943926bcd8d8b328cb0
  Stored in directory: /home/dechin/.cache/pip/wheels/b6/a3/ad/dd6a4edcfd25a175d263a4e67d231f903982fdde6f10727913
  Building wheel for hiq-projectq (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dechin/git_lab/hiq/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbls51fj/hiq-projectq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbls51fj/hiq-projectq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iivlw5e2
       cwd: /tmp/pip-install-sbls51fj/hiq-projectq/
  Complete output (221 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/projectq
  copying projectq/_version.py -> build/lib.linux-x86_64-3.7/projectq
  copying projectq/__init__.py -> build/lib.linux-x86_64-3.7/projectq
  creating build/lib.linux-x86_64-3.7/projectq/tests
  copying projectq/tests/__init__.py -> build/lib.linux-x86_64-3.7/projectq/tests
  creating build/lib.linux-x86_64-3.7/projectq/backends
  copying projectq/backends/_json_converter.py -> build/lib.linux-x86_64-3.7/projectq/backends
  copying projectq/backends/_printer.py -> build/lib.linux-x86_64-3.7/projectq/backends
  copying projectq/backends/_resource.py -> build/lib.linux-x86_64-3.7/projectq/backends
  copying projectq/backends/__init__.py -> build/lib.linux-x86_64-3.7/projectq/backends
  creating build/lib.linux-x86_64-3.7/projectq/types
  copying projectq/types/_qubit.py -> build/lib.linux-x86_64-3.7/projectq/types
  copying projectq/types/__init__.py -> build/lib.linux-x86_64-3.7/projectq/types
  creating build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_manualmapper.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_testengine.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_ibm5qubitmapper.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_swapandcnotflipper.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_linearmapper.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_twodmapper.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_optimize.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/__init__.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  copying projectq/cengines/_tagremover.py -> build/lib.linux-x86_64-3.7/projectq/cengines
  creating build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/default.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/linear.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/grid.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/restrictedgateset.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/trapped_ion_decomposer.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/ibm.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/aqt.py -> build/lib.linux-x86_64-3.7/projectq/setups
  copying projectq/setups/__init__.py -> build/lib.linux-x86_64-3.7/projectq/setups
  creating build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_command.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_qftgate.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_state_prep.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_metagates.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_basics.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_gates.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_uniformly_controlled_rotation.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_qubit_operator.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_time_evolution.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_qpegate.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_qaagate.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_shortcuts.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/_unitary_gates.py -> build/lib.linux-x86_64-3.7/projectq/ops
  copying projectq/ops/__init__.py -> build/lib.linux-x86_64-3.7/projectq/ops
  creating build/lib.linux-x86_64-3.7/projectq/libs
  copying projectq/libs/__init__.py -> build/lib.linux-x86_64-3.7/projectq/libs
  creating build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_util.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_control.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_loop.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_dirtyqubit.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_dagger.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_logicalqubit.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/__init__.py -> build/lib.linux-x86_64-3.7/projectq/meta
  copying projectq/meta/_compute.py -> build/lib.linux-x86_64-3.7/projectq/meta
  creating build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  copying projectq/backends/_circuits/_to_latex.py -> build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  copying projectq/backends/_circuits/_drawer_matplotlib.py -> build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  copying projectq/backends/_circuits/_plot.py -> build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  copying projectq/backends/_circuits/_drawer.py -> build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  copying projectq/backends/_circuits/__init__.py -> build/lib.linux-x86_64-3.7/projectq/backends/_circuits
  creating build/lib.linux-x86_64-3.7/projectq/backends/_sim
  copying projectq/backends/_sim/_pysim.py -> build/lib.linux-x86_64-3.7/projectq/backends/_sim
  copying projectq/backends/_sim/_classical_simulator.py -> build/lib.linux-x86_64-3.7/projectq/backends/_sim
  copying projectq/backends/_sim/_simulator.py -> build/lib.linux-x86_64-3.7/projectq/backends/_sim
  copying projectq/backends/_sim/__init__.py -> build/lib.linux-x86_64-3.7/projectq/backends/_sim
  creating build/lib.linux-x86_64-3.7/projectq/backends/_aqt
  copying projectq/backends/_aqt/_aqt_http_client.py -> build/lib.linux-x86_64-3.7/projectq/backends/_aqt
  copying projectq/backends/_aqt/_aqt.py -> build/lib.linux-x86_64-3.7/projectq/backends/_aqt
  copying projectq/backends/_aqt/__init__.py -> build/lib.linux-x86_64-3.7/projectq/backends/_aqt
  creating build/lib.linux-x86_64-3.7/projectq/backends/_ibm
  copying projectq/backends/_ibm/_ibm.py -> build/lib.linux-x86_64-3.7/projectq/backends/_ibm
  copying projectq/backends/_ibm/_ibm_http_client.py -> build/lib.linux-x86_64-3.7/projectq/backends/_ibm
  copying projectq/backends/_ibm/__init__.py -> build/lib.linux-x86_64-3.7/projectq/backends/_ibm
  creating build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/_swap_utils.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/_basics.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/_basicmapper.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/_main.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/_cmdmodifier.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  copying projectq/cengines/_core/__init__.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_core
  creating build/lib.linux-x86_64-3.7/projectq/cengines/_replacer
  copying projectq/cengines/_replacer/_replacer.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_replacer
  copying projectq/cengines/_replacer/_decomposition_rule_set.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_replacer
  copying projectq/cengines/_replacer/_decomposition_rule.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_replacer
  copying projectq/cengines/_replacer/__init__.py -> build/lib.linux-x86_64-3.7/projectq/cengines/_replacer
  creating build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/ph2r.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/rx2rz.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/cnot2rxx.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/arb1qubit2rzandry.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/qft2crandhadamard.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/amplitudeamplification.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/qubitop2onequbit.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/toffoli2cnotandtgate.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/sqrtswap2cnot.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/stateprep2cnot.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/time_evolution.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/r2rzandph.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/h2rx.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/ry2rz.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/swap2cnot.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/phaseestimation.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/uniformlycontrolledr2cnot.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/cnot2cz.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/globalphase.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/unitary2rzry.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/crz2cxandrz.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/rz2rx.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/cunitary2rzry.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/carb1qubit2cnotrzandry.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/barrier.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/cnu2toffoliandcu.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/entangle.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  copying projectq/setups/decompositions/__init__.py -> build/lib.linux-x86_64-3.7/projectq/setups/decompositions
  creating build/lib.linux-x86_64-3.7/projectq/libs/math
  copying projectq/libs/math/_gates.py -> build/lib.linux-x86_64-3.7/projectq/libs/math
  copying projectq/libs/math/_default_rules.py -> build/lib.linux-x86_64-3.7/projectq/libs/math
  copying projectq/libs/math/_constantmath.py -> build/lib.linux-x86_64-3.7/projectq/libs/math
  copying projectq/libs/math/__init__.py -> build/lib.linux-x86_64-3.7/projectq/libs/math
  creating build/lib.linux-x86_64-3.7/projectq/libs/hist
  copying projectq/libs/hist/_histogram.py -> build/lib.linux-x86_64-3.7/projectq/libs/hist
  copying projectq/libs/hist/__init__.py -> build/lib.linux-x86_64-3.7/projectq/libs/hist
  creating build/lib.linux-x86_64-3.7/projectq/libs/revkit
  copying projectq/libs/revkit/_control_function.py -> build/lib.linux-x86_64-3.7/projectq/libs/revkit
  copying projectq/libs/revkit/_phase.py -> build/lib.linux-x86_64-3.7/projectq/libs/revkit
  copying projectq/libs/revkit/_permutation.py -> build/lib.linux-x86_64-3.7/projectq/libs/revkit
  copying projectq/libs/revkit/_utils.py -> build/lib.linux-x86_64-3.7/projectq/libs/revkit
  copying projectq/libs/revkit/__init__.py -> build/lib.linux-x86_64-3.7/projectq/libs/revkit
  running build_ext
  creating tmp
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmphuyvzmg9.cpp -o tmp/tmphuyvzmg9.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  ---------------------------------------------------------------------------
  # INFO:  Configuring OpenMP
  ---------------------------------------------------------------------------
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmpsw_zualm.cpp -o tmp/tmpsw_zualm.o -openmp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmpgraqw96o.cpp -o tmp/tmpgraqw96o.o -fopenmp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ tmp/tmpgraqw96o.o -o /tmp/tmpbpn_kxmu/test -fopenmp
  ---------------------------------------------------------------------------
  # INFO:  Configuring compiler intrinsics
  ---------------------------------------------------------------------------
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmpo8kn6eob.cpp -o tmp/tmpo8kn6eob.o -march=native
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmp49aeruea.cpp -o tmp/tmp49aeruea.o -ffast-math
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  ---------------------------------------------------------------------------
  # INFO:  Configuring C++ standard
  ---------------------------------------------------------------------------
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmplj6k9lmk.cpp -o tmp/tmplj6k9lmk.o -std=c++17
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  ---------------------------------------------------------------------------
  # INFO:  Other compiler tests
  ---------------------------------------------------------------------------
  gcc -pthread -B /home/dechin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dechin/git_lab/hiq/include -I/home/dechin/anaconda3/include/python3.7m -c /tmp/tmpj3amhoj8.cpp -o tmp/tmpj3amhoj8.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  ---------------------------------------------------------------------------
  # INFO:  Finished configuring compiler!
  ---------------------------------------------------------------------------
  building 'projectq.backends._sim._cppsim' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sbls51fj/hiq-projectq/setup.py", line 482, in <module>
      run_setup(True)
    File "/tmp/pip-install-sbls51fj/hiq-projectq/setup.py", line 460, in run_setup
      **kwargs)
    File "/home/dechin/git_lab/hiq/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/dechin/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dechin/git_lab/hiq/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/dechin/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dechin/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-sbls51fj/hiq-projectq/setup.py", line 221, in run
      build_ext.run(self)
    File "/home/dechin/git_lab/hiq/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-sbls51fj/hiq-projectq/setup.py", line 231, in build_extensions
      build_ext.build_extensions(self)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/dechin/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/dechin/git_lab/hiq/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/ccompiler.py", line 566, in compile
      depends, extra_postargs)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/ccompiler.py", line 341, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/home/dechin/anaconda3/lib/python3.7/distutils/ccompiler.py", line 1075, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
    File "/tmp/pip-install-sbls51fj/hiq-projectq/setup.py", line 63, in __str__
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  ----------------------------------------
  ERROR: Failed building wheel for hiq-projectq
  Running setup.py clean for hiq-projectq
Successfully built hiq-circuit mpi4py
Failed to build hiq-projectq
Installing collected packages: mpi4py, numpy, future, wcwidth, attrs, more-itertools, py, six, pyparsing, packaging, zipp, importlib-metadata, pluggy, pytest, pybind11, urllib3, idna, chardet, certifi, requests, scipy, decorator, networkx, cycler, python-dateutil, kiwisolver, matplotlib, hiq-projectq, hiq-circuit
    Running setup.py install for hiq-projectq ... done
Successfully installed attrs-19.3.0 certifi-2020.4.5.2 chardet-3.0.4 cycler-0.10.0 decorator-4.4.2 future-0.18.2 hiq-circuit-0.0.2 hiq-projectq-0.6.3 idna-2.9 importlib-metadata-1.6.1 kiwisolver-1.2.0 matplotlib-3.2.1 more-itertools-8.4.0 mpi4py-3.0.3 networkx-2.4 numpy-1.18.5 packaging-20.4 pluggy-0.13.1 py-1.8.2 pybind11-2.5.0 pyparsing-2.4.7 pytest-5.4.3 python-dateutil-2.8.1 requests-2.23.0 scipy-1.4.1 six-1.15.0 urllib3-1.25.9 wcwidth-0.2.4 zipp-3.1.0
```

**Comment by Takishima** [comment]
Which version of pip are you using?
Are you using a virtualenv?

Could you try to manually install the `pybind11` package?

**Comment by Takishima** [comment]
Did you manage to get the installation issue fixed?

**Comment by DechinPhy** [comment]
I do not know why but when I remove the '--user' option this installation will success sometimes. But there are still some problem in my server, which is broken for weeks and I did not do more tests. I will try to find more servers with different OS to do test for this installation method. Thank you for reply!
