### ISSUE TITLE
[BUG] Cannot install by pip  

### ISSUE THREAD

**Issue by keithyau** [Huawei-HiQ/HiQsimulator#47]
**Describe the bug**
python3 -m pip install --user .

**To Reproduce**
Steps to reproduce the behavior. 
python3 -m pip install --user .

**Expected behavior**
Processing /Users/keithyau/src/QC/HiQsimulator
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ms/vcn8nf4944b2cg701928w6th0000gn/T/pip-req-build-yt666myn/setup.py'"'"'; __file__='"'"'/private/var/folders/ms/vcn8nf4944b2cg701928w6th0000gn/T/pip-req-build-yt666myn/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/ms/vcn8nf4944b2cg701928w6th0000gn/T/pip-pip-egg-info-7o2klhgv
         cwd: /private/var/folders/ms/vcn8nf4944b2cg701928w6th0000gn/T/pip-req-build-yt666myn/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ms/vcn8nf4944b2cg701928w6th0000gn/T/pip-req-build-yt666myn/setup.py", line 7, in <module>
        from setuptools import setup, Extension, Feature, find_packages
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.9/site-packages/setuptools/__init__.py)
    ----------------------------------------
WARNING: Discarding file:///Users/keithyau/src/QC/HiQsimulator. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Please provide a [minimum working example (MWE)](https://en.wikipedia.org/wiki/Minimal_working_example) whenever possible so that we can easily address the issue.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [MacOS]
 - Python version: [e.g. 3.9.3]
 - Pip version: [e.g. 20.2.1]
 - Version of hiq-circuit: [e.g. 3.6.2]
 - Are you using a virtual environment: [e.g. yes/no]

**Additional context**

**Comment by Takishima** [comment]
This is indeed a problem that was solved in our internal development branch but has not yet been ported to the open-source version yet.

I will see if I can add those changes in the coming days.

**Comment by keithyau** [comment]
thank you, wait for your new release
